### ISSUE TITLE
Name field is missing in perfdata output

### ISSUE THREAD

**Issue by mdicss** [simply42/check_wmi_plus_wmic_dropin#10]
Hi
We want to use your wmic.py to query cpu usage for each processor. In the perfdata output, the name field is missing.
The query is
'select PercentProcessorTime,Timestamp_Sys100NS from Win32_PerfRawData_PerfOS_Processor'

Using the original wmic, I get output like:
CLASS: Win32_PerfRawData_PerfOS_Processor
Name|PercentProcessorTime|Timestamp_Sys100NS
0|29657480000000|133113627574236161
1|29602146875000|133113627574236161
_Total|29629813437500|133113627574236161

With wmic.py, I only get:
CLASS: Win32_PerfRawData_PerfOS_Processor
PercentProcessorTime|Timestamp_Sys100NS
29657184843750|133113627277635218
29601852812500|133113627277635218
29629518828125|133113627277635218

So we have no name-field to name the different cpu's.
The according output of check_wmi_plus is now:
OK (Sample Period 104 sec) - CPU=1.0%   CPU=0.9%   CPU=0.9%   |'Avg Utilisation CPU'=1.0%;101;101; 'Avg Utilisation CPU'=0.9%;101;101; 'Avg Utilisation CPU'=0.9%;101;101;
So we see three times the same name.

I did not succeed to create a pach, yet. It would be great to have a solution here. There is no 'name' in 'record' in wmic.py.

Regards, Matthias

**Comment by wornet-aer** [comment]
Hi Matthias,

this workaround for wmic has been built when there was no official solution for `check_wmi_plus`. However since version no. 1.67 support for https://github.com/cesbit/aiowmi/tree/main/contrib/wmic_server has been implemented by the developers. Maybe you want to give this new architecture a try - it will probably be the best supported solution.

Otherwise you can also try the python wmic replacement done by https://github.com/dlundgren/py-wmi-client.

In case you have a fix for our wmic.py we're happy to review your pull request.
Thanks for your contribution!

Cheers,
Andreas

**Comment by mdicss** [comment]
Hi Andreas
I did a test with https://github.com/dlundgren/py-wmi-client . This seems to work, but I first had to change the script for python3 and I only testes the eachcpu so far. Maybe it is better to switch back to check_wmi_plus and use the version with the wmic server.
Thank you
Matthias

**Comment by mdicss** [comment]
Hi Andreas
I found the problem with eachcpu. In the query, defined in check_wmi_plus.ini, which comes with the check_wmi_plus skript, there is the 'Name' field missing. The query should be:

query=select Name,PercentProcessorTime,Timestamp_Sys100NS from Win32_PerfRawData_PerfOS_Processor
